one: https://github.com/Armen-Jean-Andreasian/License-header-injector
two: https://github.com/Armen-Jean-Andreasian/Fifa22-Icons-Unlocked
three: https://github.com/Armen-Jean-Andreasian/Active-Erroring
four: https://github.com/Armen-Jean-Andreasian/ADG-Anti-DDOS-Guard
five: https://github.com/Armen-Jean-Andreasian/the-directory-scanner
six: https://github.com/Armen-Jean-Andreasian/File-encryptor-for-Python
seven: https://github.com/Armen-Jean-Andreasian/File-Encryptor-for-Ruby
eight: https://github.com/Armen-Jean-Andreasian/Selfie-AI
nine: https://github.com/Armen-Jean-Andreasian/Github-Chad
ten: https://github.com/pyenv/pyenv
eleven: https://github.com/Qiskit/qiskit