name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (production)
        run: |
          pip install -r requirements.txt

      - name: Install dev dependencies (for testing)
        run: |
          pip install -r dev-requirements.txt

      - name: Run tests
        run: |
          pytest tests  # Run your tests directory with pytest

      - name: Upload coverage report (optional)
        if: success()
        run: |
          # Optionally upload coverage report if you're using one
          pip install coverage
          coverage report
